# Generated by Django 5.2.1 on 2025-05-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='has_dj',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='venue',
            field=models.CharField(default='Main', max_length=100),
            preserve_default=False,
        ),
    ]
