# Generated by Django 5.2.1 on 2025-05-19 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shift_comment_shift_has_dj_shift_is_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.dj')),
            ],
        ),
    ]
