# Generated by Django 5.2.1 on 2025-12-29 06:46

from django.db import migrations


def add_dj_nada(apps, schema_editor):
    DJ = apps.get_model('core', 'DJ')
    DJ.objects.get_or_create(name='Nada')

def remove_dj_nada(apps, schema_editor):
    DJ = apps.get_model('core', 'DJ')
    DJ.objects.filter(name='Nada').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.RunPython(add_dj_nada, remove_dj_nada),
    ]
