# Generated by Django 5.2.1 on 2025-12-30 04:29

from django.db import migrations


def rename_nada_to_nadine(apps, schema_editor):
    DJ = apps.get_model('core', 'DJ')
    DJ.objects.filter(name='Nada').update(name='Nadine')

def rename_nadine_to_nada(apps, schema_editor):
    DJ = apps.get_model('core', 'DJ')
    DJ.objects.filter(name='Nadine').update(name='Nada')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_dj_nada'),
    ]

    operations = [
        migrations.RunPython(rename_nada_to_nadine, rename_nadine_to_nada),
    ]
